# Playbook with conditional example
---
- name: Playbook with conditional example
  hosts: labservers
  tasks:
   - name: Check conditional in ansible
     shell: uptime
     register: uptime_stat
     when: ansible_hostname == 'ansible-node2'
     
   - name: Display uptime
     debug: var=uptime_stat