# Playbook to stop Linux Firewall

- name: Stopping iptables
  service: name=iptables state=stopped enabled=no
  register: iptables_status
  when: ansible_distribution_major_version < '7'
  
- name: Stopping iptables
  service: name=firewalld state=stopped enabled=no
  register: iptables_status
  when: ansible_distribution_major_version >= '7'
  
- debug: msg="IPTables is stopped now"