# Playbook to stop Linux Firewall

- name: Stopping iptables
<<<<<<< HEAD
  service: name=iptables state=stopped enabled=no
  register: iptables_status
  when: ansible_distribution_major_version < '7'
  
- name: Stopping iptables
  service: name=firewalld state=stopped enabled=no
  register: iptables_status
  when: ansible_distribution_major_version >= '7'
=======
  service: iptables state=stopped enabled=no
  register: iptables_status
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' and ansible_distribution_version <= '6'
  
- name: Stopping iptables
  service: iptables state=stopped enabled=no
  register: iptables_status
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' and ansible_distribution_version == '7'
>>>>>>> ac2a817dd95f52ab8fdbeda550932de1c442b56f
  
- debug: msg="IPTables is stopped now"