# Playbook to install a simple web application

- name: Deploy a simple web application
  hosts: webservers
  vars:
   - db_name: database
   - db_user: user
   - db_password: password
  tasks:
   - name: Check installed Python version
     shell: `which rpm` -qa python | cut -d'-' -f2
     register: python_ver
      when: python_ver <= 2.7.0
      role: python-update
     
   - name: Install Development tools
     yum: name="@Development Tools" state=installed

   - name: Install Python
     yum: name={{ item }} state=installed
     with_items:
      - python
      - python-setuptools
      - python-devel
      - python-pip
      - MySQL-python
      
   - name: Install MySQL Server and Client
     yum: name={{ item }} state=installed
     with_items:
      - mysql-server
      - mysql

   - name: Start MySQL service
     service:
       name: mysqld
       state: started
       enabled: yes

   - name: Create Application Database
     mysql_db: 
       name: '{{ db_name }}'
       state: present

   - name: Create Database User
     mysql_user:
       name: '{{ db_user }}'
       password: '{{ db_password }}'
       priv: '*.*:ALL'
       state: present

   - name: Install Python Flask dependency
     pip:
      name: '{{ item }}'
      state: present
     with_items:
       - flask
       - flask-mysql
       
   - name: Copy Source Code to target server
     copy: src=app.py dest=/opt/app.py
     
   - name: Start the webserver
     shell: export FLASK_APP=/opt/app.py && nohup python -m flask run --host=0.0.0.0 &