# Playbook to install a simple web application

- name: Deploy a simple web application
  hosts: webservers
  vars:
   - db_name: database
   - db_user: user
   - db_password: password
  roles:
     - { role: python-update, when: ansible_python_version > 2.7 }
  #   - stop-firewall
  tasks:
   - name: Installing Development tools
     yum: name="@Development Tools" state=installed
     
   - name: Installing Python addtionals
     yum: name={{ item }} state=installed
     with_items:
      - python
      - python-setuptools
      - python-devel
      - python-pip
      - MySQL-python
     when: 'ansible_python_version < 2.7'
      
   - name: Installing MySQL Server and Client
     yum: name={{ item }} state=installed
     with_items:
      - mysql-server
      - mysql

   - name: Starting MySQL service
     service:
       name: mysqld
       state: started
       enabled: yes

   - name: Creating Application Database
     mysql_db: 
       name: '{{ db_name }}'
       state: present

   - name: Creating Database User
     mysql_user:
       name: '{{ db_user }}'
       password: '{{ db_password }}'
       priv: '*.*:ALL'
       state: present

   - name: Installing Python Flask dependency
     pip:
      name: '{{ item }}'
      executable: pip2.7
      state: present
     with_items:
       - flask
       - flask-mysql
       
   - name: Copying Source Code to target server
     copy: src=app.py dest=/opt/app.py
     
   - name: Starting the webserver
     shell: |
      export FLASK_APP=/opt/app.py
      nohup python2.7 -m flask run --host=`ip a | grep eth0 | grep inet | cut -d '/' -f1 | awk '{print $2}'` &
     
   - debug: msg="Now you can browse the website at http://{{ ansible_all_ipv4_addresses }}:5000"